trigger-actions-framework/main/default/objects/Trigger_Action_Populator_Override__mdt/Trigger_Action_Populator_Override__mdt.object-meta.xml
<CustomObject>
    <description>Field populators for Trigger Actions</description>
    <label>Trigger Action Populator</label>
    <pluralLabel>Trigger Action Populators</pluralLabel>
</CustomObject>

trigger-actions-framework/main/default/objects/Trigger_Action_Populator_Override__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Activation Flag</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action_Populator_Override__mdt/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>Name of apex class storing populator</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action_Populator_Override__mdt/fields/Before_Insert__c.field-meta.xml
<CustomField>
    <fullName>Before_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Executes in Before Insert Context</description>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action_Populator_Override__mdt/fields/Before_Update__c.field-meta.xml
<CustomField>
    <fullName>Before_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Executes in Before Update context</description>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action_Populator_Override__mdt/fields/sObject_Trigger_Setting__c.field-meta.xml
<CustomField>
    <fullName>sObject_Trigger_Setting__c</fullName>
    <description>Parent SObject for the populators</description>
    <label>sObject Trigger Setting</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>Trigger Action Populators</relationshipLabel>
    <relationshipName>Trigger_Action_Populators</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

trigger-actions-framework/main/default/classes/klaviyo-extensions/populator/PopulatorOverrideSelectorTest.cls
@isTest(isParallel=true)
private class PopulatorOverrideSelectorTest {
    @IsTest
    static void byParentId() {
        // Test
        String soql = PopulatorOverrideSelector.query().byInactive().toString();

        // Verify
        Assert.areEqual('SELECT Apex_Class_Name__c, Active__c, Before_Insert__c, Before_Update__c, sObject_Trigger_Setting__c FROM Trigger_Action_Populator_Override__mdt WHERE Active__c = :v1', soql, 'The generated SOQL should include Active__c filter.');
    }

    @IsTest
    static void byBeforeInsert() {
        // Test
        String soql = PopulatorOverrideSelector.query().byBeforeInsert().toString();

        // Verify
        Assert.areEqual('SELECT Apex_Class_Name__c, Active__c, Before_Insert__c, Before_Update__c, sObject_Trigger_Setting__c FROM Trigger_Action_Populator_Override__mdt WHERE Before_Insert__c = :v1', soql, 'The generated SOQL should include Before_Insert__c filter.');
    }

    @IsTest
    static void byBeforeUpdate() {
        // Test
        String soql = PopulatorOverrideSelector.query().byBeforeUpdate().toString();

        // Verify
        Assert.areEqual('SELECT Apex_Class_Name__c, Active__c, Before_Insert__c, Before_Update__c, sObject_Trigger_Setting__c FROM Trigger_Action_Populator_Override__mdt WHERE Before_Update__c = :v1', soql, 'The generated SOQL should include Before_Update__c filter.');
    }

    @IsTest
    static void byActive() {
        // Test
        String soql = PopulatorOverrideSelector.query().byActive().toString();

        // Verify
        Assert.areEqual('SELECT Apex_Class_Name__c, Active__c, Before_Insert__c, Before_Update__c, sObject_Trigger_Setting__c FROM Trigger_Action_Populator_Override__mdt WHERE Active__c = :v1', soql, 'The generated SOQL should include Active__c filter.');
    }

    @IsTest
    static void bySObjectTriggerSettingObjectAPIName() {
        // Test
        String soql = PopulatorOverrideSelector.query().bySObjectTriggerSettingObjectAPIName('Account').toString();

        // Verify
        Assert.areEqual('SELECT Apex_Class_Name__c, Active__c, Before_Insert__c, Before_Update__c, sObject_Trigger_Setting__c FROM Trigger_Action_Populator_Override__mdt WHERE sObject_Trigger_Setting__mdt__r.Object_API_Name__c = :v1', soql, 'The generated SOQL should include sObject_Trigger_Setting__mdt__r.Object_API_Name__c filter.');
    }
}