trigger-actions-framework/main/default/objects/Trigger_Action_Populator_Override__mdt/Trigger_Action_Populator_Override__mdt.object-meta.xml
<CustomObject>
    <description>Field populators for Trigger Actions</description>
    <label>Trigger Action Populator</label>
    <pluralLabel>Trigger Action Populators</pluralLabel>
</CustomObject>

trigger-actions-framework/main/default/objects/Trigger_Action_Populator_Override__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Activation Flag</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action_Populator_Override__mdt/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>Name of apex class storing populator</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action_Populator_Override__mdt/fields/Before_Insert__c.field-meta.xml
<CustomField>
    <fullName>Before_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Executes in Before Insert Context</description>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action_Populator_Override__mdt/fields/Before_Update__c.field-meta.xml
<CustomField>
    <fullName>Before_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Executes in Before Update context</description>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action_Populator_Override__mdt/fields/sObject_Trigger_Setting__c.field-meta.xml
<CustomField>
    <fullName>sObject_Trigger_Setting__c</fullName>
    <description>Parent SObject for the populators</description>
    <label>sObject Trigger Setting</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>Trigger Action Populators</relationshipLabel>
    <relationshipName>Trigger_Action_Populators</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

trigger-actions-framework/main/default/classes/klaviyo-extensions/populator/PopulatorOverrideSelector.cls
public inherited sharing class PopulatorOverrideSelector extends SOQL implements SOQL.Selector {
    @TestVisible
    private static final String MOCK_ID = 'PopulatorOverrideSelector';

    public static PopulatorOverrideSelector query() {
        return new PopulatorOverrideSelector();
    }

    private PopulatorOverrideSelector() {
        super(Trigger_Action_Populator_Override__mdt.SObjectType);
        with(Trigger_Action_Populator_Override__mdt.Apex_Class_Name__c, Trigger_Action_Populator_Override__mdt.Active__c, Trigger_Action_Populator_Override__mdt.Before_Insert__c, Trigger_Action_Populator_Override__mdt.Before_Update__c, Trigger_Action_Populator_Override__mdt.sObject_Trigger_Setting__c);
        mockId(MOCK_ID);
    }

    public PopulatorOverrideSelector byInactive() {
        whereAre(Filter.with(Trigger_Action_Populator_Override__mdt.Active__c).equal(false));
        return this;
    }

    public PopulatorOverrideSelector byBeforeInsert() {
        whereAre(Filter.with(Trigger_Action_Populator_Override__mdt.Before_Insert__c).equal(true));
        return this;
    }

    public PopulatorOverrideSelector byBeforeUpdate() {
        whereAre(Filter.with(Trigger_Action_Populator_Override__mdt.Before_Update__c).equal(true));
        return this;
    }

    public PopulatorOverrideSelector byActive() {
        whereAre(Filter.with(Trigger_Action_Populator_Override__mdt.Active__c).equal(true));
        return this;
    }
    

    public PopulatorOverrideSelector bySObjectTriggerSettingObjectAPIName(String sobjectName) {
        whereAre(Filter.with('sObject_Trigger_Setting__mdt__r', sObject_Trigger_Setting__mdt.Object_API_Name__c).equal(sobjectName));
        return this;
    }
}